### ISSUE TITLE
error : from models.grids import * ModuleNotFoundError: No module named 'models.grids'

### ISSUE THREAD

**Issue by wlupc** [alvaro-budria/NeuSacc#1]
Thanks good job. when I run this project, there is an error.  from models.grids import * ModuleNotFoundError: No module named 'models.grids' , the 'grids' file does not exist at 'models' folder. please public the 'grids' file. Looking forward to your reply.

**Comment by alvaro-budria** [comment]
Thanks for your interest. I forgot to remove that line when cleaning the code. The latest code in `main` should now work fine. Feel free to reopen this issue or a new one if necessary.
