### ISSUE TITLE
confs/wandb_config.yaml is empty?

### ISSUE THREAD

**Issue by wlupc** [alvaro-budria/NeuSacc#3]
Thanks your previous reply. I find the config file 'wandb_config.yaml' is empty, but the following code is using the config file,
in the file "exp_runner.py", 
133   config_dict = {"yaml": "confs/wandb_config.yaml"}
134         self.run = wandb.init(
135            project="NeuS-Enhanced", config=config_dict, save_code=True, dir=self.base_exp_dir,
136        ) 

This will cause an error, I am not sure. Look forward to your review. :)

**Comment by alvaro-budria** [comment]
Thanks for the observation. Indeed this wandb config is useless, but it is definitely not causing any errors. Nevertheless I just removed it as it is not needed.
