### ISSUE TITLE
404 not found in https://github.com/NVlabs/tiny-cuda-nn/@8e6e242f36dd197134c9b9275a8e5108a8e3af78

### ISSUE THREAD

**Issue by JerryPW** [alvaro-budria/NeuSacc#8]
Hi! Thanks for your update in NeuS. 
However, there is a 404 not found in link: "https://github.com/NVlabs/tiny-cuda-nn/@8e6e242f36dd197134c9b9275a8e5108a8e3af78", which always cause unsuccessful installation. Could you update your requirement.txt to the updated link?

**Comment by alvaro-budria** [comment]
Hi Jerry, thanks a lot for your interest. It seems that this link to the repo is indeed down.
I am currently not maintaining this repo though, as I moved my focus to a slightly different topic, and there are already other up-to-date resources. I keep this repo only for reference and showcasing.
I recommend you check this repo https://github.com/bennyguo/instant-nsr-pl. It is very complete and is basically very similar to mine.
